In [32]:
import numpy as np
a = np.array((3, 2), int)
a

array([3, 2])

In [33]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [34]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a


array([1, 2, 3])

In [35]:
np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array((1, 2), dtype=int)

In [ ]:
lang = np.array(['파이썬'*3, '자바', '씨'], dtype='<U3')
lang

In [ ]:
np.arange(-3, 3, 0.5, dtype=int)

In [ ]:
np.arange(-3, 3, 0.5)

In [ ]:
np.linspace(0.1, 0.4, 3, endpoint=True)

In [ ]:
np.linspace(0.1, 0.4, 3, endpoint=False)

In [ ]:
np.ones((2, 4, 3))

In [ ]:
np.ones((2, 4))

In [ ]:
np.empty((3, 2, 3), int)

In [ ]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum()

In [ ]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum(axis=1)

In [ ]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum(axis=2)

In [ ]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum(axis=0)

In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

In [ ]:
np.transpose(a)

In [ ]:
np.transpose(a, (0, 1))

In [ ]:
np.transpose(a, (1, 0))

In [ ]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

In [ ]:
np.transpose(c, (2, 0, 1))

In [ ]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

In [ ]:
np.swapaxes(x, 0, 1)

In [ ]:
import numpy as np
a = np.arange(24)
a.ravel()

In [ ]:
a.flat()

In [ ]:
a.ravel()

In [42]:
x= np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])

In [43]:
np.c_[x, y]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [38]:
np.r_[x,y]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [40]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])