In [59]:
import numpy as np
a = np.array((3, 2), int)
a

array([3, 2])

In [119]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [121]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a


array([1, 2, 3])

In [126]:
np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [130]:
np.array((1, 2), dtype=int)

array([1, 2])

In [132]:
lang = np.array(['파이썬'*3, '자바', '씨'], dtype='<U3')
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [133]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [134]:
np.arange(-3, 3, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [136]:
np.linspace(0.1, 0.4, 3, endpoint=True)

array([0.1 , 0.25, 0.4 ])

In [137]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [138]:
np.ones((2, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [140]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [154]:
np.empty((3, 2, 3), int)

array([[[4128860, 6029375, 3801155],
        [5570652, 6619251, 7536754]],

       [[5046364, 5177433, 5111893],
        [8257607, 6029361, 7340097]],

       [[4456560, 7602273, 6029409],
        [7274572, 6357091,     108]]])

In [155]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum()

array([ 10,  30,  35,  43,  44,  46, 146, 346, 396, 476, 486, 506])

In [156]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum(axis=1)

array([[[ 10,  20],
        [ 15,  28],
        [ 16,  30]],

       [[100, 200],
        [150, 280],
        [160, 300]]])

In [157]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum(axis=2)

array([[[ 10,  30],
        [  5,  13],
        [  1,   3]],

       [[100, 300],
        [ 50, 130],
        [ 10,  30]]])

In [158]:
a = np.array([[[10, 20], [5, 8], [1, 2]], [[100, 200], [50, 80], [10, 20]]])
a.cumsum(axis=0)

array([[[ 10,  20],
        [  5,   8],
        [  1,   2]],

       [[110, 220],
        [ 55,  88],
        [ 11,  22]]])

In [160]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [163]:
np.transpose(a, (0, 1))

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
np.transpose(a, (1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [165]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [166]:
np.transpose(c, (2, 0, 1))

array([[[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]],

       [[ 3,  6],
        [ 9, 12]]])

In [167]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [168]:
np.swapaxes(x, 0, 1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])