In [1]:
import numpy as np

x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [2]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [3]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [4]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [76]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [78]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [79]:
a.ravel()

array([ 0, 10, 20, 30])

In [80]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
fl = x.flat
type(fl)

numpy.flatiter

In [83]:
for item in fl:
    print(item)

0
1
2
3
4
5


In [5]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [8]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [9]:
from numpy import array

a = array([3, 4, 5])
a

array([3, 4, 5])

In [12]:
import numpy as np

a = np.array([3, 4, 5])
a

array([3, 4, 5])

In [10]:
b = 2
b

2

In [13]:
a + b

array([5, 6, 7])

In [14]:
from numpy import array

A = array([[1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

In [17]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
y = arange(-1, 2)
y

#[[-1, 0, 1]
#[-1, 0, 1]
#[-1, 0, 1]]

array([-1,  0,  1])

In [19]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
y = arange(3, 10, 3).reshape(3, 1)
y

#[[3, 3,3]
#[6, 6, 6]
#[9, 9, 9]]

array([[3],
       [6],
       [9]])

In [21]:
np.set_printoptions

<function numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)>

In [22]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [23]:
from numpy import arange

x = arange(1, 4)
x

#[[1, 2, 3]
#[1, 2, 3]
#[1, 2, 3]]

array([1, 2, 3])

In [24]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [25]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [26]:
x / y

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [27]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [28]:
y = arange(1, 3)
y

array([1, 2])

In [29]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [30]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [31]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [35]:
np.newaxis is None

True

In [33]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [34]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [36]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [37]:
a.shape

(4, 1)

In [38]:
from numpy import array

b = array([1, 2, 3])
b

array([1, 2, 3])

In [39]:
b

array([1, 2, 3])

In [40]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [43]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [45]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [47]:
print(x[[2]])
print(x[[2, 3]])

[2]
[2 3]


In [48]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [49]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [50]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [51]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [52]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
x[[0]]

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [54]:
x[0, 1]

1

In [55]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [56]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [58]:
x[[0], [1]]

array([1])

In [59]:
# 0, 1행
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [60]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [62]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [63]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [65]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [67]:
# 첨자 [1, 2]과 [3, 2]에 해당하는 11과 26
x[[1, 3], [3, 2]]

array([11, 26])

In [68]:
# 1, 3행의 2열
x[[1,3], [2]]

array([10, 26])

In [69]:
# 1, 3행의 2열
x[[1,3], 2]

array([10, 26])

In [70]:
# 첨자 [1, 3]과 [3, 3]에 해당하는 11과 27
x[[1,3], [3, 3]]

array([11, 27])

In [71]:
x[[1, 3], [3]]

array([11, 27])

In [72]:
from numpy import array

x[array([0, 2, 4]), arange([0, 1])]

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [73]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [74]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [75]:
x[array([0, 2, 4]), :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [84]:
import numpy as np
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [86]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [87]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [88]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [89]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [90]:
d = np.array([100, 200])
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [91]:
d = np.array([100, 200, 300])
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [93]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

In [94]:
np.r_[a, b, c]

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [95]:
import numpy as np
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [96]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [97]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [98]:
np.c_[a, b]

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [99]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [100]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [101]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [102]:
np.r_[np.arange(3), np.arange(10, 15)]

array([ 0,  1,  2, 10, 11, 12, 13, 14])

np.column_stack()

In [103]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [104]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [105]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [106]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [107]:
np.c_[a, b]

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [108]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [109]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [110]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [111]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [112]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [113]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [114]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [115]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [116]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [117]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [118]:
print(np.vstack)

<function vstack at 0x00000194A91DE700>


In [119]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [120]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [121]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [122]:
np.concatenate((a, b, c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [125]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [126]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [127]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [128]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [129]:
print(np.vstack((x, y)))
print(np.row_stack((x, y)))
print(np.r_[x, y])

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]


In [130]:
np.concatenate((x, y, z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [131]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [132]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [133]:
print(np.hstack((x, y, z)))
print(np.column_stack((x, y, z)))
print(np.c_[x, y, z])

[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]
[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]
[[ 0  1  2 10 11 12 20 21]
 [ 3  4  5 13 14 15 22 23]]


In [134]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [137]:
import numpy as np 

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [138]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [139]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [142]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [143]:
np.stack((a, b), axis=-2)

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [146]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [148]:
y = np.arange(10, 16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [149]:
z = np.arange(20, 26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [151]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [152]:
ax0.shape

(3, 2, 3)

In [154]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [155]:
ax1.shape

(2, 3, 3)

In [156]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [157]:
ax2.shape

(2, 3, 3)

In [158]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [159]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [160]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [161]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [162]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [166]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [167]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [164]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [165]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [168]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [169]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [170]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [171]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [172]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [173]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [174]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [175]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [176]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [177]:
np.c_[a, c]

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [178]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [180]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [181]:
np.row_stack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [182]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [183]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [184]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [185]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [186]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [187]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [188]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [189]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

np.r_

In [190]:
np.r_['1, 2', [1, 2], [[10, 20]]]

array([[ 1,  2, 10, 20]])

In [191]:
np.r_['1, 2', [[1], [2], [10], [20]]]

array([[ 1],
       [ 2],
       [10],
       [20]])

In [192]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [193]:
np.r_((a, b))

TypeError: 'RClass' object is not callable

In [194]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [195]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [197]:
np.r_[-1:1:6, [0]*2, 5, 6]

array([-1,  0,  0,  5,  6])

In [198]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [199]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [200]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [201]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [202]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [203]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [204]:
np.r_['0, 2', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [205]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [206]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [210]:
arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])
print(arr[:, None])
print(arr[np.newaxis, :])
print(arr[None, :])

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1 2 3]]


In [211]:
np.expand_dims(arr, 1)

array([[1],
       [2],
       [3]])

In [256]:
np.expand_dims?

Signature:       np.expand_dims(a, axis)
Call signature:  np.expand_dims(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function expand_dims at 0x00000194A9325580>
File:            c:\users\myoungjin\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Expand the shape of an array.

Insert a new axis that will appear at the `axis` position in the expanded
array shape.

Parameters
----------
a : array_like
    Input array.
axis : int or tuple of ints
    Position in the expanded axes where the new axis (or axes) is placed.

    .. deprecated:: 1.13.0
        Passing an axis where ``axis > a.ndim`` will be treated as
        ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
        be treated as ``axis == 0``. This behavior is deprecated.

    .. versionchanged:: 1.18.0
        A tuple of axes is now supported.  Out of range axes as
        described above are now forbidden and raise an `AxisError`.

Re

In [214]:
np.expand_dims(arr, axis=(0, 1))

array([[[1, 2, 3]]])

In [215]:
np.expand_dims(arr, axis=(1, 0))

array([[[1, 2, 3]]])

In [216]:
np.expand_dims(arr, axis=(2, 0))

array([[[1],
        [2],
        [3]]])

In [217]:
np.expand_dims(arr, axis=(2, 0)).shape

(1, 3, 1)

In [218]:
np.expand_dims(arr, axis=(2, 1))

array([[[1]],

       [[2]],

       [[3]]])

In [219]:
np.expand_dims(arr, axis=(2, 1)).shape

(3, 1, 1)

In [220]:
np.expand_dims(arr, axis=(1, 0))

array([[[1, 2, 3]]])

In [222]:
np.expand_dims[np.array([1, 2, 3]), 2] # 1차원인데 2차원이 없이 건너뛰고 3차원을 만들려고 하니 에러가 난다.

TypeError: 'numpy._ArrayFunctionDispatcher' object is not subscriptable

In [223]:
np.expand_dims(np.array([1, 2, 3]), axis=(1, 2))

array([[[1]],

       [[2]],

       [[3]]])

In [224]:
np.expand_dims(np.array([4, 5, 6]), axis=(1, 2))

array([[[4]],

       [[5]],

       [[6]]])

In [225]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [226]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape
# 3, 1, 1
# 3, 1, 1
# ----
# 6, 1, 1

(6, 1, 1)

In [227]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]
# 1, 3, 1
# 1, 3, 1
# ----
# 2, 3, 1

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [229]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 2)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 2)))


[[[1]
  [2]
  [3]]]
[[[4]
  [5]
  [6]]]


In [230]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape

(2, 3, 1)

In [232]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]
# 1, 1, 3
# 1, 1, 3
# ----
# 2, 1, 3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [233]:
print(np.expand_dims(np.array([1, 2, 3]), axis=(0, 1)))
print(np.expand_dims(np.array([4, 5, 6]), axis=(0, 1)))

[[[1 2 3]]]
[[[4 5 6]]]


In [234]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]].shape

(2, 1, 3)

In [235]:
print(np.r_[[1, 2, 3], [4, 5, 6]])

# 2차원 매트릭스 생성
np.r_['r', [1, 2, 3], [4, 5, 6]]

[1 2 3 4 5 6]


matrix([[1, 2, 3, 4, 5, 6]])

In [237]:
np.r_['c', [[1, 2, 3]], [[4, 5, 6]]]

matrix([[1, 2, 3],
        [4, 5, 6]])

In [238]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [239]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [240]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [241]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [242]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [243]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [244]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [245]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [247]:
np.r_['0, 2', a, b]

array([[1, 2, 3],
       [4, 5, 6]])

In [248]:
np.concatenate((a[np.newaxis, :], b[np.newaxis]))

array([[1, 2, 3],
       [4, 5, 6]])

In [249]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [250]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [251]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [252]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [253]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [254]:
np.r_['1, 2, 0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [257]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [258]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    casting : {'no', 'equiv', 'safe', 'same_kind', 

In [259]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [260]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [261]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [262]:
y = np.array([[5, 6]])

In [263]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [264]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [265]:
y.T

array([[5],
       [6]])

In [266]:
np.concatenate((x, y.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [267]:
x.flatten()

array([1, 2, 3, 4])

In [268]:
y.flatten()

array([5, 6])

In [269]:
np.concatenate((x, y), axis=None)

array([1, 2, 3, 4, 5, 6])

In [270]:
import numpy as np

x = np.arange(9.0)
x


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [273]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [274]:
print(type(s))
print(s[0])

<class 'list'>
[0. 1. 2.]


In [275]:
np.split(x, 4)

ValueError: array split does not result in an equal division

In [276]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [277]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [278]:
s = np.split(x, 3)
s

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [279]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [280]:
np.split(y, [2, 3, 4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [281]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int32)]

In [282]:
y[4:6]

array([50, 60])

In [283]:
y[6:]

array([], dtype=int32)

In [285]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [286]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [287]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [288]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [289]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [290]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int32)]

In [291]:
a = np.arange(10)

In [292]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

np.vsplit()

In [297]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.vsplit(a, 4)

In [ ]:
np.vsplit(a, [1, 4, 6])

In [ ]:
a[:1, :]

In [ ]:
a[3:6, :]

In [ ]:
x = np.arange(10).reshape(2, 4)

In [ ]:
np.split(x, 2)

In [ ]:
x[:, :2, :]

In [ ]:
x[:, 2:, :]

In [310]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [311]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [312]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [313]:
np.split(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [314]:
x[:2, :, :]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [315]:
x[2:, :, :]

array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [316]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [317]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [318]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [319]:
x[3:1]

array([], shape=(0, 4, 2), dtype=int32)

In [320]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [321]:
help(np.array_split)

Help on _ArrayFunctionDispatcher in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.

    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.

    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
    [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]

    >>> x = np.arange(9)
    >>> np.array_split(x, 4)
    [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]



In [322]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [323]:
np.array_split(x, 2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [324]:
np.split(x, 2)

ValueError: array split does not result in an equal division

In [325]:
import numpy as np

np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [327]:
np.array_split(x, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [328]:
np.array_split(x, 5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [329]:
np.array_split(x, [2, 4, 8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

In [332]:
import numpy as np

a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [333]:
np.array_split(a, 4, axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [334]:
np.array_split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [335]:
np.array_split(a, 4, axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [337]:
np.array_split(a, [2, 4], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [339]:
import numpy as np

x = np.arange(24).reshape(2, 2, 6)  #2, 2, 1, 1
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [340]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [341]:
np.split(x, [2, 4, 5], axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [342]:
x[:, :, 5:]

array([[[ 5],
        [11]],

       [[17],
        [23]]])

In [343]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [344]:
np.dsplit(x, 2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [345]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [346]:
np.dsplit(x, 4)

ValueError: array split does not result in an equal division

In [347]:
x[:, :, 4:]

array([[[ 4,  5],
        [10, 11]],

       [[16, 17],
        [22, 23]]])

In [348]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x194A9EA3AE0

In [349]:
r = rg.random()
r

0.22733602246716966

In [350]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [351]:
rg.random((4, 3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [352]:
import numpy as np

rg = np.random.default_rng(12345)
r = rg.integers(low=0, high=10, size=3)
r

array([6, 2, 7], dtype=int64)

In [353]:
rg.integers(1, 7, (3, 4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]], dtype=int64)

In [354]:
import numpy as np

rg = np.random.default_rng(seed=42)
rg.standard_normal(10)

array([ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472, -1.95103519,
       -1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [355]:
rg.standard_normal((4, 3))

array([[ 0.87939797,  0.77779194,  0.0660307 ],
       [ 1.12724121,  0.46750934, -0.85929246],
       [ 0.36875078, -0.9588826 ,  0.8784503 ],
       [-0.04992591, -0.18486236, -0.68092954]])